QUERY_TYPE_DEFINITION = "definition"
QUERY_TYPE_COMPARISON = "comparison"
QUERY_TYPE_RECOMMENDATION = "recommendation"

ALLOWED_QUERY_TYPES = {
    QUERY_TYPE_DEFINITION,
    QUERY_TYPE_COMPARISON,
    QUERY_TYPE_RECOMMENDATION,
}